name: build

on:
  push:
    tags:
    - 'v*'
    branches:
    - '**'
    pull_request:
      types: [opened, synchronize, reopened]

jobs:
  build-linux:
    name: Build Linux SDL2
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        build_type: [debug, release]
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 1
    - uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    - run: pip install meson ninja
    - run: |
        sudo apt update 
        sudo apt install git libsdl2-dev
    - name: Configure
      run: meson setup builddir/ --buildtype ${{ matrix.build_type }}
      env:
        CC: gcc-12
        CXX: g++-12
    - name: Compile
      run: meson compile -C builddir/

  build-psp:
    name: Build PSP
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        build_type: [debug, release]
    container: zie87/pspdev:latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 1
    - name: Configure
      run: meson setup builddir/ --cross-file ./tools/psp/mips_psp_elf.build --buildtype ${{ matrix.build_type }}
    - name: Compile
      run: meson compile -C builddir/

  build-ps2:
    name: Build PS2
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        build_type: [debug, release]
    container: zie87/ps2dev:latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 1
    - name: Configure
      run: meson setup builddir/ --cross-file ./tools/ps2/mips64r5900el_ps2_ee.build --buildtype ${{ matrix.build_type }}
    - name: Compile
      run: meson compile -C builddir/

  build-mingw:
    name: Build MinGW SDL2
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        build_type: [debug, release]
    container: zie87/mingw:latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 1
    - name: Configure
      run: meson setup builddir/ --cross-file ./tools/win/x86_64-w64-mingw32.build --buildtype ${{ matrix.build_type }} --force-fallback-for=sdl2
    - name: Compile
      run: meson compile -C builddir/
